export const LogicActionsArray: string[] = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "period",
  "equals",
  "clear",
  "flip",
  "percent",
  "divide",
  "multiply",
  "subtract",
  "sum",
]

export const LogicActionsObject = {
  zero: "zero",
  one: "one",
  two: "two",
  three: "three",
  four: "four",
  five: "five",
  six: "six",
  seven: "seven",
  eight: "eight",
  nine: "nine",
  period: "period",
  equals: "equals",
  clear: "clear",
  flip: "flip",
  percent: "percent",
  divide: "divide",
  multiply: "multiply",
  subtract: "subtract",
  sum: "sum",
}
